# ServerProperties
server:
  port: 81
#server.servlet.context-path=/myblog

comment:
  avatar: https://cdn.jsdelivr.net/gh/starmilkxin/picturebed/img/lol%E9%9A%8F%E6%9C%BA


#经过jasypt加密
address: ENC(Mo9MT7gq6X0jj0G+sONLez3kiQACtp8Q)

spring:
  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${address}/myblog?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(ZwwqCyn6iX3NB+Md304OHw==)
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 15
      minimum-idle: 5
    password: ENC(X33v+aQJ+5SrphzXlbHWp0eWmip8QZQQ)
    type: com.zaxxer.hikari.HikariDataSource
  # Redis
  redis:
    database: 1
    host: ${address}
    password: ENC(AaLkrjBHKf/u5XPctkvUqzq/sJGnqdtO)
    port: 6379
  #Kafka
  kafka:
    bootstrap-servers: ENC(icI90qK5i/WdEv1xLTzaRgEhvjuDFAPrizXVf0qhvxY=)
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: myblog-consumer-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


# MybatisProperties
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    useGeneratedKeys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xin.myblog.pojo

# logger
#logging:
#  file:
#    path: log/myblog.log
#  level:
#    com:
#      xin:
#        myblog: info
#    root: info

#指定加密算法
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES

#指定密钥
#jasypt.encryptor.password=***

#JWT对称加密
jwt:
  secret: ENC(7GLL1otKl6E+9CXA+kQY0WdjR3wOvE0Z)
